# Generated by Django 4.0.4 on 2022-06-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantify',
            new_name='quantity',
        ),
    ]
